[book]
authors = [
]
language = "de"
multilingual = false
src = "src"
title = "Wiki – FabLab Bad Windsheim"

[output.html]
git-repository-url = "https://github.com/fablab-nea/wiki"
edit-url-template = "https://github.com/fablab-nea/wiki/edit/master/{path}"
